---
- name: Pull docker image of the Calculator
  hosts: all
  tasks:
    - name: pull docker image
      shell: docker pull ksaraswat/backend
      
#     - name: run docker image backend
#       shell: docker run -it -d ksarawat/backend /bin/bash
