version: "3.3"
services:

  mysqldb-container:
    image: mysql
    container_name: mysqldb-container
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3308:3306"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password

  backend:
    image: ksaraswat/backend
    container_name: backend
    tty: true
    environment:
      - SPRING_DATABASE_URL=jdbc:mysql://mysqldb-container:3306/SPE?createDatabaseIfNotExist=true
    ports:
      - "8084:8084"
    restart: on-failure
    links:
      - mysqldb-container
    depends_on:
      - mysqldb-container
  frontend:
    image: "ksaraswat/frontend"
    container_name: frontend
    ports:
      - 4200:4200

volumes:
  mysql-data:
