version: "2.4"
services:

  mysqldb-container:
    image: mysql/mysql-server
    container_name: mysqldb-container
#    volumes:
#      - mysql-data:/var/lib/mysql
    networks:
      - my_net
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=SPE
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password

  backend:
    image: ksaraswat/backend
    container_name: backend
    networks:
      - my_net
    ports:
      - "8084:8084"
    links:
      - mysqldb-container
    depends_on:
      mysqldb-container:
        condition: service_healthy

  frontend:
    image: ksaraswat/frontend
    container_name: frontend
    networks:
      - my_net
    ports:
      - "4200:4200"
    depends_on:
      - backend

#volumes:
#  mysql-data:

networks:
  my_net:
