version: "3.3"
services:

  mysqldb-container:
    image: mysql
    container_name: mysqldb-container
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  Backend:
    image: ksaraswat/backend
    container_name: Backend
    tty: true
    ports:
      - "8082:8080"
    links:
      - mysqldb-container
    depends_on:
      - mysqldb-container

volumes:
  mysql-data:
